services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gameplatform_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=gameplatform;Username=gameuser;Password=gamepassword;
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gameplatform_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: gameplatform_postgres
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepassword
      POSTGRES_DB: gameplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/DockerForPostgree/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameuser -d gameplatform"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gameplatform_network
    restart: unless-stopped

networks:
  gameplatform_network:
    name: gameplatform_network

volumes:
  postgres_data: